#ifndef CONFIG_INLINE_STEPPER_HACK
#define CONFIG_INLINE_STEPPER_HACK 0
#endif
#ifndef CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE
#define CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE 0
#endif
#ifndef CONFIG_MACH_AVR
#define CONFIG_MACH_AVR 0
#endif
#ifndef CONFIG_EXPERIMENTAL_LOAD_CELL_RETRACT
#define CONFIG_EXPERIMENTAL_LOAD_CELL_RETRACT 1
#endif
#define CONFIG_CLOCK_FREQ 12000000
